# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

warnings_are_errors: true
language: R
sudo: false
cache: packages
repros:
  MRAN: "https://mran.microsoft.com/snapshot/2017-07-20"
addons:
  apt:
    packages:
      - libudunits2-dev
      - libgdal-dev
      - libgsl0-dev
      - gdal-bin
      - libgeos-dev
      - libpng-dev
      - libproj-dev
script:
  - Rscript -e "options(repos = '$MRAN')"
  - Rscript -e "rmarkdown::render('analysis/TestPackage.Rmd')"


