# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
repros:
  MRAN: "https://mran.microsoft.com/snapshot/2017-07-20"
script: Rscript -e "options(repos = '$MRAN')"


